antvis/component

- src/legend/category.js
问题描述：https://riddle.alibaba-inc.com/riddles/d4701fe3
由于legendGroup缺少viewId字段，导致在https://github.com/antvis/g2/blob/97a67f1626e41fcf663f864763b7c1fa42ca66f8/src/chart/view.js#L273
时，无法正确比较
修复方案：
增加set方法将viewId填充到legendGroup属性上
> 修复无法触发legend-item:click事件的bug

- src/label/base.js
Fix https://github.com/antvis/g2/issues/1069
> 修复传入axis中label的textStyle的rotate只有第一个字段生效的bug

- .travis.yml
- package.json
- src/tooltip/canvas.js
- src/tooltip/html.js
- src/tooltip/mixin/marker-group.js
* tooltip中的marker 改成使用svg实现，这样可以渲染常见的图标
* tooltip中能够读取activeSymbol / symbol，来渲染图形对应的图标
[g2 相关PR](https://github.com/antvis/g2/pull/1359)
> feature: 支持设置geom中tooltip对应点的形状

- src/tooltip/html.js
见 [G2 issue 1349](https://github.com/antvis/g2/issues/1349)，在使用 `htmlContent` 属性自定义 tooltip 的时候，css 样式不对
> fix(tooltip): fix position property when use htmlContent for tooltip

- src/axis/base.ts
- src/axis/line.ts
- tests/unit/axis/circle-spec.ts
- tests/unit/axis/line-spec.ts
默认 title 的 offset 自动计算，当用户设置了则以用户值为准。
关联 G2 issue: https://github.com/antvis/G2/issues/2412
> fix(axis): 修复坐标轴 title offset 无法生效的问题

- package.json
- src/util/util.ts
- tests/unit/axis/empty-line-spec.ts
fixed https://github.com/antvis/G2Plot/issues/1243
当 axis 中 line label 等都为空的时候，会导致 getLayoutBBox 返回为 NaN，从而导致上层布局挂掉。
> fix(axis): when line, label all is null

- src/axis/base.ts
- tests/bugs/issue-axis-style-callback.ts
原先的 style 返回的是所有的 ticks，这样就导致如果坐标轴文本自动隐藏的时候，index 对应的一些文本被隐藏，设置不生效。
style 回调提供的参数应该是最后显示在图表上的 items。而不是原先全量的 items.
这里先处理下 label，解决业务迫切问题，tickLine 也要处理下，这个后面提交 PR
> fix(axis): label  style 回调的参数应该是调整完后的值

- package.json
- src/axis/overlap/auto-hide.ts
- src/util/util.ts
- tests/unit/axis/auto-hide-spec.ts
- tests/unit/axis/line-spec.ts
关联 https://github.com/antvis/G2/issues/2592
> fix(axis): improve auto hide overlap

- src/axis/line.ts
- src/axis/overlap/auto-rotate.ts
- tests/unit/axis/auto-title-spec.ts
修复标题重叠问题 https://github.com/antvis/G2Plot/issues/1820
现有代码在设置 title offset 时没有考虑 label rotated 的情况， 直接使用了 bbox 的 width 或 height ， 在用户设置了 label rotate 或者触发 autoRotate 时需要重新计算 bbox ， 加上 rotate 产生的 maxLength。
> fix: 修复 axis title offset

- src/axis/line.ts
- src/axis/overlap/auto-hide.ts
- src/types.ts
- tests/unit/axis/auto-hide-spec.ts
- tests/unit/axis/line-spec.ts
axis label autoHide 支持配置最小间距:
```js
xAxis: {
label: {
autoRotate: false,
autoHide: {
type: 'equidistance',
cfg: {
minGap: 6,
},
},
},
},
```
| before | after|
|--- | --- |
| ![image](https://user-images.githubusercontent.com/1142242/100538364-517cfd00-326a-11eb-9a09-1ba080ad86a9.png)| ![image](https://user-images.githubusercontent.com/1142242/100538359-3f02c380-326a-11eb-953a-dcd451a7af6f.png)|
> feat: support minGap cfg for autoHide overlap

- src/legend/category.ts
- src/types.ts
- tests/unit/legend/category-spec.ts
通过 对  绘制文本方法 进行 style 的 适配。达到回调的实现。
> feat:  添加 itemName style 回调

- src/legend/category.ts
- src/legend/continuous.ts
- src/types.ts
- tests/unit/legend/category-spec.ts
- tests/unit/legend/continuous-spec.ts
> Fix legend values

- src/legend/category.ts
- tests/unit/legend/category-flippage-spec.ts
> fix:  【legend】 期望分页场景下的多行和不分页的多行，展示一致

- src/axis/circle.ts
- src/axis/overlap/auto-ellipsis.ts
- src/scrollbar/scrollbar.ts
- src/util/label.ts
- tests/unit/annotation/line-spec.ts
- tests/unit/annotation/text-spec.ts
- tests/unit/axis/auto-ellipsis-spec.ts
- tests/unit/crosshair/html-spec.ts
针对[#2487](https://github.com/antvis/G2Plot/issues/2487)修复
> fix(#2487): 圆型坐标轴支持文本缩略

- src/util/theme.ts
follow this fix 👍 https://github.com/antvis/G2/pull/3640/files
> fix: safari15 对-apple-system 字体支持有问题导致页面卡死

- package.json
- src/legend/category.ts
- src/types.ts
- tests/unit/legend/category-radio-spec.ts
给图例增加正反选按钮，参考这个 [issue](https://github.com/antvis/G2/issues/3736)。
默认不开启，具体的功能参考下图。
```js
const legend = new CategoryLegend({
id: 'c',
container,
x: 100,
y: 100,
updateAutoRender: true,
itemBackground: null,
items: [
{ name: 'a', value: 123, marker: { symbol: 'square', style: { r: 4, fill: '#5B8FF9' } } },
// 只有 showRadio 为 true 才会显示出来，否者 opacity 为 0 只是一个占位符
{ name: 'b', value: 223, showRadio: true, marker: { symbol: 'square', style: { r: 4, fill: '#5AD8A6' } } },
{ name: 'c', value: 323, marker: { symbol: 'square', style: { r: 4, fill: '#5D7092' } } },
],
// 开启并设置样式
radio: {
fill: 'red',
stroke: 'blue'
}
});
```
> feat(legend): 添加正反选按钮

- src/abstract/component.ts
在Chart还未渲染出来前，将鼠标移动Chart上，并快速移动，会出现如下错误
```
component.js:75 Uncaught TypeError: Cannot read property 'marker' of undefined
at component.js:75
at each (each.js:19)
at Tooltip.push../node_modules/@antv/component/esm/abstract/component.js.Component.update (component.js:70)
at Tooltip.push../node_modules/@antv/g2/esm/chart/controller/tooltip.js.Tooltip.showTooltip (tooltip.js:87)
at Chart.push../node_modules/@antv/g2/esm/chart/view.js.View.showTooltip (view.js:856)
at TooltipAction.push../node_modules/@antv/g2/esm/interaction/action/component/tooltip/geometry.js.TooltipAction.showTooltip (geometry.js:63)
at TooltipAction.push../node_modules/@antv/g2/esm/interaction/action/component/tooltip/geometry.js.TooltipAction.show (geometry.js:36)
at executeAction (grammar-interaction.js:26)
at …
```
> fix(component): set default value for defaultCfg

- src/annotation/html.ts
- src/types.ts
- tests/unit/annotation/html-spec.ts
> fix(annotation): 修复html 组件 html参数为 数字、空字符串 以及 特殊字符时出现的报错问题

- src/tooltip/html.ts
tooltip 有2种展示方式, 默认的和自定义的. 而自定义的tooltip在跟随鼠标移动时, 会表现的卡顿. 实际原因就是dom的transition没有生效, 根本原因是每次鼠标滑动都会产生一个新的dom, 然后执行replaceChild.
> fix(tooltip): 修复自定义 tooltip 的动画没有 transition 效果

- src/tooltip/html.ts
- tests/unit/tooltip/html-spec.ts
在之前的版本中, `customContent`必须返回一个DOM, 否则会没有效果. 本次修改就是修复了这个场景问题, 无论`customContent`返回什么, 都能够顺利出现在`tooltip`组件中.
> fix(tooltip): 修复当 customContent 传入非 DOM 或单一 DOM 结构无法渲染的问题

- src/tooltip/html.ts
- tests/unit/tooltip/html-spec.ts
> Revert "fix(tooltip): 修复当 customContent 传入非 DOM 或单一 DOM 结构无法渲染的问题"

- src/abstract/html-component.ts
- src/tooltip/css-const.ts
- src/tooltip/html-theme.ts
- src/tooltip/html.ts
- tests/unit/tooltip/html-spec.ts
为了减少大家的思考复杂度, 在简述部分不多说了, 直接看下方留言的小作文就好.
> fix(tooltip): 修复 tooltip transition 不生效以及线上兼容问题

- package.json
- src/slider/constant.ts
- src/slider/foreground.ts
- src/slider/handler.ts
- src/slider/slider.ts
- src/util/event.ts
- src/util/mask.ts
- src/util/util.ts
- tests/unit/component/group-simple-spec.ts
- tests/unit/legend/legend-animate-spec.ts
- tests/unit/slider/handler-spec.ts
- tests/unit/slider/slider-spec.ts
设计稿：https://done.alibaba-inc.com/share/file/UnfMwBa6RLfSgFTQ?pageId=FB673644-9B49-4E46-A95F-CBB4C8DBD077&aid=9538D5EF-0A95-47FC-800B-FA116006ABA8&m=SPECS
- **背景区域支持 Brush Interaction**
- **选中区域 foreground 更新为三部分：**
- 上 3/5：Brush Interaction
- 下 2/5：Move Interaction
- 下方新增 Bar：Move Interaction
- handler 更新为小方块
- Trend 更新颜色，添加面积区域
- foreground 增加外边框
- 检测为日期型文字时，通过空格截断，两行显示：
- 普通文本换行显示，超长时省略：
> refactor(slider): update UI & add brush interaction.

- src/slider/constant.ts
- src/slider/foreground.ts
- src/slider/slider.ts
- src/util/event.ts
- src/util/mask.ts
- src/util/util.ts
- tests/unit/component/group-simple-spec.ts
- 修复 slider 组件移动端移动事件失效问题
- 修复 slider 组件在长文本下文字
| Before | After |
|--------|-------|
| <img width="246" alt="image" src="https://user-images.githubusercontent.com/109653633/219596239-0683b974-2dc0-4d18-bc24-d6dad23b63ac.png"> | <img width="227" alt="image" src="https://user-images.githubusercontent.com/109653633/219596368-0adaa070-9301-4a66-96c5-7be43a333760.png"> |
- 支持传入 barStyle 定制下方 bar 样式
> fix(slider): move interaction does not work in mobile & fix text size bug

- package.json
- src/slider/constant.ts
- src/slider/foreground.ts
- src/slider/handler.ts
- src/slider/slider.ts
设计体验优化
- 交换选中区域内框选和拖动的位置：用户的框选操作更倾向从上往下，框选放在下方更符合用户习惯。
- 拖动过程中，保持住滑块的高亮颜色
> feat: change brush and move position & hode highlight fill when move

- package.json
- src/slider/constant.ts
- src/slider/foreground.ts
- src/slider/handler.ts
- src/slider/slider.ts
- tests/unit/slider/handler-spec.ts
样式问题修复。业务方对这些属性的要求较多，所以改为支持可配置。
- 文本位置调整支持业务层定制：`textStyle.dodgeText`
- 刷选区域的占比支持业务层定制：`foregroundStyle.brushRatio`
- 添加滑块柄， `handler` 新增一条小竖线
- 文本间距支持业务层定制: `textStyle.padding`
> feat: dodgeText and brushRatio support receive from user

- src/annotation/data-marker.ts
- src/types.ts
- tests/unit/annotation/data-marker-spec.ts
希望可以在0.8.x版本里 让dataMarker类型标注功能支持更多的朝向
- dataMarker类型标注功能支持更多的朝向：'leftward' | 'rightward'
- 对dataMarker类型标注的自动布局进行了优化
> Feat: add more datamarker annotation direction

- CHANGELOG.md
- package.json
- src/axis/base.ts
- src/types.ts
- tests/unit/axis/circle-spec.ts
业务需要根据轴标签之间的间距来决定显示的文本长度和换行，所以业务方需要通过 formatter 函数得到轴间距。
因此，在 `axis.label.formatter` 中加入 ticks 参数，能够得到前后 label 的坐标信息。可以根据坐标信息得到轴间距。
```js
axis.label.formatter: (text, tick, index, ticks) => {
const newPoint = ticks[index+1].point; // 下一个 label 坐标
const curPoint = tick.point; // 当前 label 坐标
const interval = newPoint.x - curPoint.x;
// 处理换行...
return newText;
}
```
> feat: axis.label.formatter add more params for custom

- src/annotation/data-marker.ts
- tests/unit/annotation/data-marker-spec.ts
- dataMarker类型标注连线的绘制进行了修复
- 对dataMarker类型标注的自动布局进行了优化
> fix: 修复datamarker自动调整下文本与文本背景偏移存在偏差

- src/axis/base.ts
- src/types.ts
- tests/unit/axis/circle-spec.ts
极端场景，当图表仅有一个一条数据时。坐标轴标签超长情况处理需要根据X轴整体宽度决定。所以提供 cfg 参数，供业务层做定制。
```js
xAxis: {
label: {
formatter: (text, tick, index, ticks, cfg) => {
const { start, end } = cfg;
const axisWidth = Math.abs(end.x - start.x);
// handle ellipse
}
}
}
```
> feat: add cfg in formatter params

- __tests__/unit/util/style-spec.ts
- package.json
- src/ui/axis/guides/labels.ts
- src/ui/axis/guides/line.ts
- src/ui/axis/guides/ticks.ts
- src/ui/axis/guides/utils.ts
- src/ui/legend/continuous.ts
- src/ui/tooltip/index.ts
- src/util/text.ts
> chore: remove deprecated dom-util

- package.json
- src/util/text.ts
使用 document 创建 `<canvas>` 进行文本连弟度量，会导致服务端渲染强依赖 node-canvas。
此时可以参考 plot 使用一个字符宽度查找表进行估算，因此需要提供一个可传入的 mock 方法实现：
```ts
import { setMockMeasureTextWidth } from '@antv/component';
setMockMeasureTextWidth(measureText);
```
目前 G2 在截图测试中使用。
> fix: provide a mock function to measure text width

- package.json
- src/core/types.ts
- src/ui/legend/continuous.ts
- src/ui/slider/index.ts
- ref https://github.com/antvis/G2/issues/5791
* before 
* after
* the issue: [legend、slider、scrollbar 涉及到鼠标拖拽的，都需要设置鼠标样式为手型 ](https://github.com/antvis/G2/issues/5791)
> fix: change the scrollbar and legend hover style.

- package.json
- src/ui/tooltip/index.ts
- src/util/index.ts
- src/util/replace-children.ts
- [ant-design-charts 2.1.0，Chrome 83.0.4103.122 图标tooltip展示有失效](https://github.com/ant-design/ant-design-charts/issues/2614)
> fix: replaceChildren compatible with lower versions

- .vscode/settings.json
- __tests__/integration/snapshots/Marker1.svg
- docs/components/legend.md
- src/ui/legend/category/item.ts
- src/ui/legend/category/items.ts
- src/ui/marker/index.ts
- src/ui/marker/symbol.ts
category 增加 focus icon
和 legend maker 相同，图形在 component 定义，事件在 g2 绑定
在 g2 中配置示例
```
.legend({
focus: true,
focusMarkerSize: 12
})
```
> feat: add legend focus icon
