- src/label/base.js
> Label refactor

- src/label/base.js
- test/unit/label/label-base-spec.js
> fix(label-base): add definition of labelLine container

- src/legend/base.js
- src/legend/category.js
- test/unit/legend/base-spec.js
- test/unit/legend/cat-html-spec.js
- test/unit/legend/cat-page-html-spec.js
- test/unit/legend/category-spec.js
> fix:change canvas size bug

- src/tooltip/canvas.js
- src/tooltip/crosshair.js
- src/tooltip/html.js
- test/unit/tooltip/canvas-spec.js
* canvas tooltip item marker对应geom
* 修复canvas tooltip board size不正确
* 修复canvas版本，tooltip、crosshair和markergroup的zIndex不正确
* canvas版本，tooltip和crosshair一开始要设置为隐藏状态
> fix tooltip bugs

- src/tooltip/canvas.js
- src/tooltip/crosshair.js
- src/tooltip/html.js
- src/tooltip/mini.js
- src/tooltip/mixin/position.js
* 修复htmlTooltip中htmlContent接口相关问题
* 修复miniTooltip包围盒取值问题
* 加回position属性相关逻辑 TAT
> fix(tooltip):htmlContent

- src/legend/base.js
- src/legend/category.js
- src/legend/color.js
- src/legend/continuous.js
- test/unit/legend/size-circle-spec.js
> fix: formatter and itemFormatter compatibility

- src/label/base.js
- src/label/utils/greedy.js
- src/label/utils/placement-util.js
- src/label/utils/position-adjust.js
- src/label/utils/simulate-anneal.js
- src/label/utils/spiral-adjust.js
- src/label/utils/visual-center.js
- 添加map、treemap、scatter的label布局算法
> Label layout

- src/tooltip/html.js
* html-tooltip初始化时不显示crosshairs
> fix htmlTooltip crosshairs

- src/label/base.js
- src/label/utils/greedy.js
- src/label/utils/spiral-adjust.js
> fix(label): fix greedy fill gap

- src/axis/base.js
> fix(axis): set label config

- package.json
- src/axis/base.js
- test/unit/axis/circle-spec.js
- test/unit/axis/line-spec.js
> Fix axis title

- src/axis/line.js
- test/unit/axis/line-spec.js
> feat(axis): support setting an array for label offset

- src/legend/category.js
> fix(legend): reverse marker style when item.activate() is called

- src/tooltip/mini.js
> fix(tooltip):mini tooltip show/hide

- src/label/base.js
_addLabe(item) 少传了第二个 index 参数，导致后面使用 label.formatter(v, o, index)  index 为 undefined 了。
> fix(tooltip):index argument

- src/tooltip/html.js
> fix(tooltip): merge custom style before applied to container

- src/axis/grid.js
* 将axis显示0轴线接口default value设置为false，即默认不开启
* 优化0轴线样式
> style(axis):axis zero-line style

- src/label/base.js
- test/unit/label/label-base-spec.js
> fix(label): assign name to every label inst & add unit tests

- src/axis/base.js
- src/axis/line.js
- src/const.js
- src/guide/line.js
- src/legend/base.js
- src/legend/cat-html.js
- src/legend/cat-page-html.js
- src/legend/category.js
- src/legend/continuous.js
- src/tooltip/canvas.js
- src/tooltip/html.js
- src/tooltip/mini.js
- src/tooltip/theme.js
- test/unit/axis/line-spec.js
> Feat axis auto hide labels

- src/axis/base.js
- src/axis/line.js
- test/unit/axis/line-spec.js
> feat(axis): label supports offsetX and offsetY configuration

- src/legend/cat-html.js
- src/legend/category.js
- src/legend/continuous.js
- test/unit/legend/cat-html-spec.js
- test/unit/legend/category-spec.js
- test/unit/legend/color-spec.js
> Fix legend hover

- src/tooltip/crosshair.js
> fix(tooltip): crosshairs should not update position after destroyed

- src/axis/base.js
- src/label/base.js
修复label rotate接口
- 弧度变为角度
- 移至textStyle中配置
- axis同步修改
> Fix label rotate

- src/label/base.js
- test/unit/label/label-base-spec.js
> fix(label): when htmlTemplate is set, useHtml should be true

- src/label/base.js
- test/unit/label/label-base-spec.js
> fix(label): fix labelLine renderer issue when config is disabled

- src/tooltip/crosshair.js
修复 tooltip crosshair  自定义样式失效问题
> fix tooltip crosshair style

- src/legend/cat-html.js
add a checkout before _adjustPositionOffset, if autoPosition is false, don't set inline-style
> fix(legend): autoPosition false but set inline style

- src/tooltip/html.js
Closes https://github.com/antvis/g2/issues/1171
> fix https://github.com/antvis/g2/issues/1171

- package.json
- src/axis/base.js
> Daily 0809

- package.json
- src/tooltip/mixin/position.js
Related to https://github.com/antvis/g2/issues/1414
> Fix enterable invalid

- .travis.yml
- package.json
- size-plugin.json
- webpack-dev.config.js
- webpack.config.js
Add size plugin to keep a check on file size
> add size-plugin

- package.json
- src/label/base.js
- test/bugs/issue-g2-1213-spec.js
fixed https://github.com/antvis/g2/issues/1213
> Fix label html container leak

- src/legend/cat-page-html.js
见 https://github.com/antvis/g2/issues/1351
> fix(legend): insert legend page flip to right contianer

- src/legend/cat-page-html.js
- test/unit/legend/cat-page-html-spec.js
修复legend横向布局的情况下，需要展示翻页组件的时候，翻页组件的bug，修复效果如下
> fix: 修复legend翻页控件，横向布局下的bug

- package.json
- src/tooltip/html.js
- src/tooltip/mixin/marker-group.js
关联 https://github.com/antvis/g2/pull/1517，这个合了之后发个版本，再合并 G2 的 pr
> Fix tooltip

- package.json
- src/abstract/component.ts
- src/abstract/group-component.ts
- src/abstract/html-component.ts
- src/axis/base.ts
- src/axis/circle.ts
- src/axis/line.ts
- src/grid/base.ts
- src/legend/category.ts
- src/types.ts
- src/util/matrix.ts
- src/util/util.ts
- tests/unit/legend/category-spec.ts
> Daily 1118

- package.json
- src/abstract/group-component.ts
- src/axis/circle.ts
- src/axis/index.ts
- src/axis/line.ts
- src/index.ts
- src/legend/index.ts
> feat: add getBBox method for group-component

- package.json
- src/abstract/component.ts
- src/abstract/group-component.ts
- src/annotation/arc.ts
- src/annotation/image.ts
- src/annotation/index.ts
- src/annotation/line.ts
- src/annotation/region.ts
- src/annotation/text.ts
- src/axis/circle.ts
- src/axis/line.ts
- src/intefaces.ts
- src/legend/base.ts
- src/legend/index.ts
- src/tooltip/html.ts
- src/types.ts
- src/util/matrix.ts
- tests/unit/annotation/arc-spec.ts
- tests/unit/annotation/image-spec.ts
- tests/unit/annotation/line-spec.ts
- tests/unit/annotation/region-spec.ts
- tests/unit/annotation/text-spec.ts
- tests/unit/component/component-spec.ts
* 完成 annotation
* 所有组件支持 location
> Daily 1101

- package.json
- src/abstract/group-component.ts
- src/axis/base.ts
- src/axis/circle.ts
- src/axis/index.ts
- src/axis/line.ts
- src/axis/overlap/auto-hide.ts
- src/axis/overlap/auto-rotate.ts
- src/grid/index.ts
- src/index.ts
- src/legend/index.ts
- src/tooltip/html-theme.ts
- src/tooltip/index.ts
- src/types.ts
- src/util/label.ts
- src/util/matrix.ts
- src/util/theme.ts
- tests/unit/axis/auto-hide-spec.ts
- tests/unit/axis/auto-rotate-spec.ts
- tests/unit/axis/line-spec.ts
- tests/unit/index-spec.ts
* 提供 autoHide, autoRotate 的扩展机制
* 设置坐标轴文本的区域限制
> feat(axis): avoid overlapping

- src/tooltip/html.ts
- tests/unit/tooltip/html-spec.ts
> fix(tooltip): fixed bug of tooltip

- package.json
- src/abstract/group-component.ts
- src/axis/base.ts
- src/axis/line.ts
- src/axis/overlap/auto-ellipsis.ts
- src/axis/overlap/auto-hide.ts
- src/axis/overlap/auto-rotate.ts
- src/axis/overlap/index.ts
- src/legend/category.ts
- src/types.ts
- tests/unit/axis/auto-ellipsis-spec.ts
- tests/unit/axis/auto-hide-spec.ts
- tests/unit/axis/line-spec.ts
- tests/unit/component/group-simple-spec.ts
* 修复 getBBox 的 bug， fixed #87 
* 添加自动省略，修改自动隐藏的逻辑
* 添加组件的委托事件支持
> feat(axis): add auto ellipsis

- package.json
- src/legend/category.ts
- src/legend/continuous.ts
- tests/unit/legend/category-spec.ts
* 添加 itemBackground ，增加拾取面积，同时防止 bbox 计算错误 , fixed #87
> feat(legend): fixed bug #87

- package.json
- src/legend/continuous.ts
- tests/unit/legend/continuous-spec.ts
> feat(legend): support size legend

- README.md
- src/interfaces.ts
> docs(readme): add api

- README.md
- package.json
- src/crosshair/base.ts
- src/crosshair/circle.ts
- src/crosshair/index.ts
- src/crosshair/line.ts
- src/index.ts
- src/types.ts
- src/util/util.ts
- tests/unit/crosshair/circle-spec.ts
- tests/unit/crosshair/line-spec.ts
- tests/unit/index-spec.ts
> feat(crosshair): add crosshair

- package.json
- src/axis/base.ts
* 在事件对象中可以拿到同 legend 统一的 item 属性
> Axis delegation object

- package.json
- src/abstract/group-component.ts
- src/axis/base.ts
- tests/unit/axis/line-spec.ts
- tests/unit/component/group-simple-spec.ts
* 增加统一的 component 到 delegationObject
* inactive 状态替换 unactive
> Axis inactive

- .github/workflows/ci.yml
- package.json
- src/abstract/group-component.ts
- src/legend/category.ts
- src/util/matrix.ts
- src/util/theme.ts
- src/util/util.ts
- tests/unit/legend/category-spec.ts
> feat(legend): support category legend flip page

- src/legend/category.ts
- tests/unit/legend/category-spec.ts
> fix: 修复分类图例翻页器在update过程的渲染

- package.json
- src/abstract/component.ts
- src/abstract/group-component.ts
- src/axis/base.ts
- src/legend/category.ts
- src/legend/continuous.ts
- src/types.ts
- src/util/event.ts
- tests/unit/component/component-spec.ts
- tests/unit/component/group-simple-spec.ts
- tests/unit/legend/continuous-spec.ts
- tests/unit/legend/legend-animate-spec.ts
> Delegation emit

- package.json
- src/abstract/group-component.ts
- tests/unit/legend/category-spec.ts
* 虚拟 group 更新时，复制 delegateObject 出错
> fix(update): copy element error

- package.json
- src/abstract/group-component.ts
- src/legend/continuous.ts
- src/util/event.ts
- tests/unit/legend/continuous-spec.ts
* 颜色的显示改成 clip
* 自定义事件增加 target
> fix(legend): clip track

- src/legend/category.ts
- tests/unit/legend/category-spec.ts
> refactor: 配合 G2 改造，shape.getMarker() 将样式都存储在 style 属性中

- package.json
- src/types.ts
- tests/unit/util-spec.ts
* 移除 Component 层自己的 BBox 定义，直接使用 g-base 的定义
* 添加 axis label 未定义的属性
> feat(types): change type definition

- package.json
> build: release 0.5.0-beta.17

- package.json
- src/abstract/component.ts
- src/abstract/group-component.ts
- src/axis/line.ts
- src/interfaces.ts
- src/legend/base.ts
- tests/unit/axis/line-spec.ts
- tests/unit/legend/category-spec.ts
> feat(bbox): add getLayoutBBox

- package.json
- src/annotation/data-marker.ts
- src/annotation/data-region.ts
- src/annotation/index.ts
- src/annotation/region-filter.ts
- src/types.ts
- src/util/util.ts
- tests/unit/annotation/data-marker-spec.ts
- tests/unit/annotation/data-region-spec.ts
- tests/unit/annotation/region-filter-spec.ts
- tests/util/dom.ts
> feat: annotation组件dataMarker dataRegion RegionFilter

- src/types.ts
> chore: 参数可选

- src/crosshair/base.ts
- tests/unit/crosshair/circle-spec.ts
> fix: textBackground can be set null

- src/annotation/text.ts
- src/legend/category.ts
- src/types.ts
- src/util/theme.ts
- tests/bugs/issue-legend-spec.ts
- tests/unit/annotation/text-spec.ts
- tests/unit/legend/category-spec.ts
* legend active 更改透明度
* annotation 支持 rotate
> feat(annoation): text roate

- src/legend/continuous.ts
- tests/unit/legend/continuous-spec.ts
> feat(continuous): drag track

- src/legend/category.ts
> fix: do not set clip for legend when flipPage is false

- src/annotation/data-region.ts
- tests/unit/annotation/data-region-spec.ts
ref: https://github.com/antvis/G2/issues/1939
修改dataRegion的配置和其他的annotation组件保持一致
> fix: data region cfg option update

- package.json
> chore: 0.5.0-beta.25

- src/legend/category.ts
- tests/unit/annotation/region-filter-spec.ts
- tests/unit/legend/category-spec.ts
- 增加regionFilter update shapes的单侧
- 图例翻页按钮按UED提供样式，增加disabbled的状态
> feat: 图例翻页样式 & regionFilter单测

- package.json
- src/abstract/component.ts
> Animate params

- src/abstract/group-component.ts
- src/slider/slider.ts
- tests/unit/slider/slider-spec.ts
> fix: 修复slider在render之前的update报错

- package.json
- src/index.ts
- src/slider/index.ts
- src/types.ts
> Export slider

- package.json
- src/annotation/data-marker.ts
- src/annotation/data-region.ts
- src/index.ts
- src/scrollbar/index.ts
- src/scrollbar/scrollbar.ts
- src/slider/slider.ts
> fix: slider默认样式 & 导出scrollbar

- package.json
- src/tooltip/html.ts
- tests/unit/tooltip/html-spec.ts
Related to https://github.com/antvis/G2/issues/2060
> tooltip marker 支持渐变色 

- src/abstract/group-component.ts
- src/legend/continuous.ts
- src/util/util.ts
- tests/unit/group-util-spec.ts
- tests/unit/util-spec.ts
* 更新的时候复制 clip
* util 里面提供 getBBoxWithClip 方法
> feat(clip): update clip

- package.json
- src/abstract/group-component.ts
- src/annotation/region-filter.ts
- src/legend/category.ts
- src/trend/path.ts
- tests/unit/legend/category-spec.ts
> fix: set clip on off-screen group for category legend

- src/legend/category.ts
- tests/unit/legend/category-spec.ts
- tests/unit/legend/legend-animate-spec.ts
> fix: correct category legend clip & navigation state

- package.json
> feat(version): 0.5.0

- package.json
> chore: add missing path-utils dep

- package.json
- src/types.ts
- src/util/align.ts
- tests/unit/legend/category-spec.ts
- tests/unit/tooltip/html-spec.ts
> feat(tooltip): tooltip position auto

- package.json
G2/G2Plot已经使用了新版的scale，旧版的scale中还有moment
> chore: update scale version

- tests/unit/legend/category-spec.ts
> test(legend): test offset

- README.md
- package.json
- src/abstract/component.ts
- src/abstract/group-component.ts
- src/abstract/html-component.ts
- src/interfaces.ts
- src/legend/category.ts
- src/types.ts
- tests/unit/component/component-spec.ts
- tests/unit/component/group-simple-spec.ts
- tests/unit/component/html-component-spec.ts
> feat(capture): add capture to all component

- package.json
- src/axis/grid.js
- src/legend/slider.js
Related to https://github.com/antvis/G2/issues/2236
> Fix constructor error

- src/abstract/component.ts
- src/annotation/text.ts
- src/legend/category.ts
- src/legend/continuous.ts
- src/tooltip/html.ts
- src/util/align.ts
- src/util/matrix.ts
- src/util/util.ts
- tests/unit/group-util-spec.ts
- tests/unit/util-spec.ts
如题，对tooltip中是否存在listDom节点进行判断，否则直接定义tooltip.container，而container中不存在G2预设模板的情况下会阻断报错。
> feat: 判断tooltip的listDom节点是否存在

- README.md
- package.json
- src/abstract/component.ts
- src/abstract/group-component.ts
- src/abstract/html-component.ts
- src/crosshair/css-const.ts
- src/crosshair/html-theme.ts
- src/crosshair/html.ts
- src/crosshair/index.ts
- src/crosshair/line.ts
- src/tooltip/html.ts
- src/types.ts
- src/util/util.ts
- tests/unit/component/group-spec.ts
- tests/unit/component/html-component-spec.ts
- tests/unit/crosshair/html-spec.ts
> Html crosshair

- package.json
> chore: update version to 0.5.5

- src/scrollbar/scrollbar.ts
- src/slider/constant.ts
- src/slider/slider.ts
- tests/unit/scrollbar/scrollbar-spec.ts
- tests/unit/slider/handler-spec.ts
- tests/unit/slider/slider-spec.ts
- tests/util/simulate.ts
> fix: unit test for scrollbar and slider

- package.json
- src/tooltip/html-theme.ts
- src/tooltip/html.ts
- tests/unit/tooltip/html-spec.ts
> feat: 支持html-tooltip的htmlContent

- src/axis/base.ts
- tests/unit/axis/line-spec.ts
关联 G2 issue: https://github.com/antvis/G2/issues/2409
> fix(axis): 修复 subTickLine style 属性无法生效的问题

- package.json
- src/legend/category.ts
- tests/unit/legend/category-spec.ts
close https://github.com/antvis/G2/issues/2311
> fix: set clip on each legend item

- package.json
- src/axis/base.ts
- src/axis/circle.ts
- src/axis/line.ts
- src/util/matrix.ts
关联 https://github.com/antvis/util/pull/45，需要等 @antv/matrix-util 发包~~
> 升级 @antv/matrix-util 

- package.json
- src/axis/base.ts
- src/types.ts
- tests/bugs/issue-axis-title-spec.ts
在只显示 axis title 的时候，需要设置默认的 offset
关联 https://github.com/antvis/G2Plot/pull/1058/files
> fix: axis title offset without label

- package.json
- src/axis/overlap/auto-ellipsis-time.ts
- src/axis/overlap/auto-ellipsis.ts
- src/axis/overlap/auto-format.ts
- src/axis/overlap/auto-wrap.ts
- src/axis/overlap/util.ts
- src/legend/responsive.ts
- src/util/text.ts
- tests/unit/axis/auto-format-spec.ts
- tests/unit/axis/auto-warp-spec.ts
- tests/unit/axis/auto-wrap-spec.ts
> add responsive method

- package.json
- src/util/align.ts
- tests/unit/tooltip/html-spec.ts
> fix: tooltip 自动位置时的冲出边缘位置调整

- package.json
> feat(version): update to 0.7.0

- src/abstract/html-component.ts
> fix: removeDom 节点不一定有parentNode

- src/axis/base.ts
- src/legend/base.ts
- src/legend/category.ts
- tests/unit/axis/line-spec.ts
- tests/unit/legend/category-spec.ts
> Add theme variable

- src/axis/base.ts
- src/grid/base.ts
- src/types.ts
- tests/bugs/issue-188-spec.ts
> feat(axis): add label, grid, tickLine style callback typedefine

- src/slider/slider.ts
- tests/unit/slider/slider-spec.ts
> fix(slider): slider 更新的时候,组合的子组件不更新的问题

- CHANGELOG.md
- package.json
> chore: release 0.7.3

- src/types.ts
> fix(types): Update AxisTitleCfg

- src/axis/line.ts
- src/axis/overlap/auto-ellipsis.ts
- src/legend/category.ts
- src/util/graphic.ts
- src/util/label.ts
- tests/bugs/issue-196-spec.ts
> fix(#196): when on autoEllipsis = true

- CHANGELOG.md
- package.json
> feat: changelog

- CHANGELOG.md
- package.json
> chore: release 0.8.3

- package.json
> fix: fix typo

- src/legend/base.ts
- tests/bugs/issue-g2-2921-spec.ts
- tests/unit/annotation/text-spec.ts
- fixed https://github.com/antvis/G2/issues/2921
- fixed https://github.com/antvis/G2Plot/issues/1729
- fixed https://github.com/antvis/G2Plot/issues/1862
> fix: 图例在设置 offset 的时候 getLayoutBBox 的 width height 不正确

- package.json
- src/index.ts
- src/util/event.ts
删除所有 lib 的引入方式，便于上层业务使用 esm 的形式打包。
> fix(esm): remove all the lib import

- package.json
- src/index.ts
- src/util/event.ts
> Upgrade tslib

- src/axis/line.ts
- tests/unit/axis/auto-title-spec.ts
| before | after |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1142242/102750760-59c7e400-43a1-11eb-9bec-e1b0b7180baa.png) | ![image](https://user-images.githubusercontent.com/1142242/102750787-69472d00-43a1-11eb-8556-d6406d466deb.png) |
close https://github.com/antvis/G2Plot/issues/2126
> fix: 修复 Axis Title offset 的自动计算逻辑

- package.json
- src/index.ts
> fix: use typescript syntax

- package.json
- src/axis/base.ts
- src/types.ts
- src/util/label.ts
- tests/unit/axis/optimize-spec.ts
- tests/unit/util-spec.ts
> fix: performance improvement by optimize large data axis

- package.json
- src/scrollbar/scrollbar.ts
- src/slider/slider.ts
- src/types.ts
- tests/unit/scrollbar/scrollbar-spec.ts
- tests/unit/slider/handler-spec.ts
- tests/unit/slider/slider-spec.ts
- 修复 slider 设置 handlerStyle 不生效
- 修复 scrollbar 设置 size 不生效
> fix: slider handler style & scrollbar size setting

- package.json
- src/slider/handler.ts
- src/slider/slider.ts
- tests/unit/slider/slider-spec.ts
> fix: slider handler style

- package.json
- src/legend/category.ts
- src/types.ts
- tests/unit/legend/category-spec.ts
> feat(legend): 图例分页器支持配置arrow marker & text 的部分样式

- README.md
- package.json
- src/legend/continuous.ts
- src/types.ts
- tests/unit/legend/continuous-spec.ts
> feat(legend): 连续型图例支持 label 进行 formatter & 单测 & 文档

- src/legend/category.ts
- src/types.ts
- tests/unit/legend/callback-spec.ts
- 使用`\\TODO`注释了单元测试中不通过的部分
- Legend 添加了Marker.symbol, Marker.style, itemName, itemValue 的回调函数
> Legend callback

- CHANGELOG.md
- package.json
> chore: v0.8.12 & add changelog

- CHANGELOG.md
- package.json
> Revert "chore: v0.8.12 & add changelog"

- src/legend/category.ts
- tests/unit/legend/category-spec.ts
1、修复`legend`组件中`item.marker.spacing`不生效
2、添加相关测试用例
> Fix legend marker spacing

- src/types.ts
close: https://github.com/antvis/G2Plot/issues/2657
> fix(types): axis title 增加 position 的类型定义

- CHANGELOG.md
- package.json
> chore: v0.8.15 & changelog

- src/legend/category.ts
- src/types.ts
- tests/unit/legend/category-flippage-spec.ts
> feat(legend): 图例支持多行分页

- CHANGELOG.md
- package.json
> chore: v0.8.6 & changelog

- src/axis/base.ts
- src/types.ts
- tests/unit/axis/line-spec.ts
- tests/unit/crosshair/html-spec.ts
[fix for #2407](https://github.com/antvis/G2Plot/issues/2407)
> fix(#2407): 坐标轴支持额外绝对偏移量

- src/util/label.ts
> bugfix: label字符省略裁切没有判断数据类型

- CHANGELOG.md
- package.json
> chore: v0.8.18 & changelog

- src/axis/circle.ts
- tests/bugs/issue-axis-circle-spec.ts
只有 `verticalLimitLength > 0` 才进行处理
> fix(axis): 修复 circle axis 处理 verticalLimitLength 不当

- CHANGELOG.md
- package.json
> chore: v0.8.19 & changelog

- src/abstract/html-component.ts
> fix: unreachable code after return statement

- src/legend/category.ts
- tests/unit/legend/category-flippage-spec.ts
close: https://github.com/antvis/G2Plot/issues/2852
|Before|After|
|---|---|
||![image](https://user-images.githubusercontent.com/15646325/137609971-7ff0b5eb-2427-448c-8417-0e55a73b072e.png)|
> fix(legend): 修复图例分页数量超过100后文字被遮挡

- package.json
> chore: update g-base version

- CHANGELOG.md
- package.json
> chore: v0.8.22 & changelog

- src/legend/category.ts
- tests/unit/legend/category-radio-spec.ts
> fix(legend): 修复 legend radio 设置错误

- CHANGELOG.md
- package.json
- src/abstract/html-component.ts
- src/legend/category.ts
- src/types.ts
> feat: legend radio 支持 tip 配置 & tooltip 支持 dom id 配置

- src/trend/path.ts
改变trend连接点y坐标点的取值逻辑（增加当trend数据全为负数时的处理逻辑）
> fix(slider): slider area trend height 过大

- CHANGELOG.md
- package.json
> chore: v0.8.25 & changelog

- src/legend/category.ts
- tests/unit/legend/category-radio-spec.ts
> feat(legend): 允许外部自定义 legend radio 透明度

- CHANGELOG.md
- package.json
> chore: v0.8.26 & changelog

- src/axis/base.ts
- src/types.ts
- src/util/theme.ts
1. 添加了坐标轴标题详细说明 icon 按钮
2. 添加了点击热区，icon 上层添加透明矩形。
> feat(axis): 添加坐标轴标题详细说明 icon 按钮

- CHANGELOG.md
- package.json
> chore: v0.8.27 & changelog

- CHANGELOG.md
- package.json
- tests/bugs/issue-annotation-html-spec.ts
> chore: v0.8.28 & changelog

- CHANGELOG.md
- package.json
> chore: 0.8.30 & changelog

- src/tooltip/html.ts
Reverts antvis/component#275
暂时先不做修改。3 个关于 Tooltip 的 PR，需要关联一起，看下影响面～
> Revert "fix(tooltip): 修复自定义 tooltip 的动画没有 transition 效果"

- CHANGELOG.md
- package.json
> chore: v0.8.32 & changelog

- src/abstract/html-component.ts
- src/tooltip/css-const.ts
- src/tooltip/html-theme.ts
- src/tooltip/html.ts
- tests/unit/tooltip/html-spec.ts
> Revert "fix(tooltip): 修复 tooltip transition 不生效以及线上兼容问题"

- CHANGELOG.md
- package.json
> Revert "chore: v0.8.32 & changelog"

- src/legend/category.ts
- tests/unit/legend/category-flippage-spec.ts
| before | after |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/65594180/217417290-1a2c53c5-c18c-42ef-9724-c2c5276d0fd5.png) | ![image](https://user-images.githubusercontent.com/65594180/217417053-d267cbd9-9ab6-4bba-a927-f95ec7e874ca.png) |
> fix(category):分页图例，分页宽度获取错误，导致部分图例被剪切

- CHANGELOG.md
- package.json
> chore: update version to 0.8.33

- CHANGELOG.md
- package.json
> chore: update to 0.8.34

- .husky/commit-msg
- .husky/pre-commit
- .npmrc
- README.md
- package.json
> chore: fix things about build

- .github/workflows/build.yml
> chore: run ci with pull request

- jest.config.js
- package.json
- src/ui/tooltip/index.ts
close: https://github.com/antvis/G2/issues/6363
close: https://github.com/ant-design/ant-design-charts/issues/2614
> fix: remove replaceChildren

- package.json
- src/ui/tooltip/index.ts
1. https://github.com/antvis/G6/issues/6135
2. https://github.com/antvis/G6/issues/6138
> fix: custom content tooltip

- tsconfig.json
Similar to https://github.com/antvis/util/pull/125
> fix: remove source root

- __tests__/integration/snapshots/AxisLinearLabelOverlapCrossSize.svg
- __tests__/integration/snapshots/AxisLinearLabelOverlapCrossSizeVertical.svg
- package.json
> chore: 2.1.3

- __tests__/integration/components/index.ts
- __tests__/integration/components/legend/index.ts
- __tests__/integration/components/legend/title.ts
- __tests__/integration/components/title/index.ts
- __tests__/unit/util/pase-position.spec.ts
- src/ui/axis/guides/title.ts
- src/ui/axis/types.ts
- src/ui/legend/category.ts
- src/ui/legend/continuous.ts
- src/ui/legend/title/index.ts
- src/ui/legend/title/types.ts
- src/ui/legend/types.ts
- src/util/index.ts
- src/util/pase-position.ts
将ui/title 移动至 ui/legend，目前这个title仅在legend中使用，并不是一个通用的title。此次移动是为了重新做一个通用的title而做的准备工作
> chore: move title to legend
